### ISSUE TITLE
cdbbulksearch: concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by robertnurnberg** [vondele/cdbexplore#19] opened 2023-05-14 13:09 UTC
Running the command `python cdbbulksearch.py ../matetrack/ChestUCI_23102018.epd --evalDecay 1 --depthLimit 12 --forever >& /tmp/rn/cdbbulk_chest.log &` eventually yields to the following abnormal termination:

```
Traceback (most recent call last):
  File "/home/rn/git/cdbexplore/cdbbulksearch.py", line 153, in <module>
    print(f.result(), flush=True)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

This has happened twice, so is not a fluke. The machine on which the command in running is a VM running Ubuntu 22.04.2 LTS.

Log attached.

[cdbbulk_chest.log](https://github.com/vondele/cdbexplore/files/11471991/cdbbulk_chest.log)

**Comment by vondele** [comment] 2023-05-14 17:18
I read this as an exception being generated by the underlying cdbsearch. Do each of the individual fens run under cdbsearch ? Could it be running into any limit on the machine (e.g. limit on the number of processes, threads, memory, etc. ?)

**Comment by robertnurnberg** [comment] 2023-05-14 17:51
The command is precisely as posted, with current version of main. So the fens will be analysed by `cdbsearch` in parallel, with bulk concurrency 4.

I agree it is probably some limit on the machine. I naively thought depthLimit 12 would be fine. ;)

**Comment by vondele** [comment] 2023-05-14 18:10
I've started that run as well. If you posted the full log it did just do 26 positions, so that should be easily reproducible? How long does it roughly take for the error to happen?

**Comment by robertnurnberg** [comment] 2023-05-14 18:14
No worries, I have restarted the job as well on a server with proper hw.

I am sure it was due to some limitations of the VM.

There it took less than a day for the error to appear.

**Comment by vondele** [comment] 2023-05-14 18:29
nice, cdbmatetrack .... 

Still strange since the first 26 positions only take very few calls (chessdbq) before returning. I wonder if something gets into an essentially unlimited extension or so and exhausts the stack. Anyway, update here if you have found more.

**Comment by vondele** [comment] 2023-05-16 11:53
I'll reopen until we understand what is causing this.

**Comment by robertnurnberg** [comment] 2023-05-16 11:59
Agreed. https://github.com/vondele/cdbexplore/pull/20 fixed my issue in the sense that the script no longer terminates.

As for the root causes: maybe the OS kills the processes because they request too much memory.

**Comment by robertnurnberg** [comment] 2023-05-16 12:25
No, not yet. You could try your raspberry pie?

**Comment by vondele** [comment] 2023-05-28 15:50
I believe this is now fixed.

**Closed by vondele** 2023-05-28 15:50 UTC
